### ISSUE TITLE
How to redraw saved Drawing?

### ISSUE THREAD

**Issue by VikasTiwari199915** [Miihir79/DrawingCanvas-Library#3]
Let's say I want to keep a drawing in a variable and draw it again whenever required, how do I do it?

//saving
ArrayList<drawingView.CustomPath> savedPaths = binding.drawingView.getDrawing();

//using it later
binding.drawingView.setDrawing(savedPath); ?? is it possible to do something like this?

**Comment by Miihir79** [comment]
Yes, It is possible to do something like that, Please feel free to Make a pull request with this feature. Thanks

**Comment by Miihir79** [comment]
It can be a function inside the DrawingView.kt file, we can do binding.drawingView.setDrawing(savedPath); -> add it in a loop (list of paths) -> mPaths.add(path) then call invalidate() to show it in the view.
